/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    jobs: Job;
    users: User;
    media: Media;
    categories: Category;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  seo?: {
    /**
     * Shown in search results and browser tabs.
     */
    title?: string | null;
    /**
     * Short summary shown in search results.
     */
    description?: string | null;
    /**
     * Used for link previews (Open Graph). Recommended 1200×630.
     */
    image?: (number | null) | Media;
  };
  blocks?:
    | {
        blocks?:
          | (
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  media?: (number | null) | Media;
                  textPosition: 'Left' | 'Right';
                  /**
                   * Controls relative width of text vs media.
                   */
                  layout: '50-50' | '40-60' | '33-67' | '25-75';
                  width?: ('auto' | 'small') | null;
                  verticalPadding?: ('none' | 'small' | 'medium' | 'large') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'ContentWithMedia';
                }
              | {
                  logo?: (number | null) | Media;
                  text?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  h1Source?: ('title' | 'custom' | 'none') | null;
                  /**
                   * Used as a visually hidden H1 for SEO
                   */
                  customH1?: string | null;
                  backgroundImage?: (number | null) | Media;
                  backgroundVideo?: (number | null) | Media;
                  overlay?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  fontSize?: ('default' | 'small' | 'large' | 'extraLarge') | null;
                  maxWidth?: ('default' | '500px') | null;
                  verticalPadding?: ('none' | 'small' | 'medium' | 'large') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'richText';
                }
              | {
                  columns?:
                    | {
                        text?: {
                          root: {
                            type: string;
                            children: {
                              type: any;
                              version: number;
                              [k: string]: unknown;
                            }[];
                            direction: ('ltr' | 'rtl') | null;
                            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                            indent: number;
                            version: number;
                          };
                          [k: string]: unknown;
                        } | null;
                        id?: string | null;
                      }[]
                    | null;
                  colWidth?: ('auto' | 'custom') | null;
                  maxColWidth?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textColumns';
                }
              | {
                  text?: string | null;
                  image?: (number | null) | Media;
                  buttonStyle: 'solid' | 'outline';
                  linkField: {
                    linkType: 'internal' | 'external';
                    url?: string | null;
                    newTab?: boolean | null;
                    internalLink?: {
                      relationTo: 'pages';
                      value: number | Page;
                    } | null;
                  };
                  alignment?: ('left' | 'center' | 'right') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'button';
                }
              | {
                  showAllPosts?: boolean | null;
                  numberOfPosts?: number | null;
                  /**
                   * Select categories to filter posts. Leave empty to show posts from all categories.
                   */
                  categoryFilter?: (number | null) | Category;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'LatestPosts';
                }
              | {
                  slides?:
                    | {
                        image: number | Media;
                        heading?: string | null;
                        subHeading?: string | null;
                        description?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'productCarousel';
                }
              | {
                  images?:
                    | {
                        media?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'mediaGallery';
                }
              | {
                  image: number | Media;
                  imageShape?: ('default' | 'variant1' | 'variant2' | 'variant3') | null;
                  aspectRatio?: ('auto' | '1/1' | '4/3' | '16/9' | '3/4' | '9/16') | null;
                  maxWidth?: ('default' | 'fullWidth' | 'custom') | null;
                  customMaxWidth?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'image';
                }
              | {
                  /**
                   * Enter the URL of the youtube video you want to embed.
                   */
                  videoURL: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'videoEmbed';
                }
              | {
                  number?: number | null;
                  heading?: string | null;
                  subheading?: string | null;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  showButton?: boolean | null;
                  button?: {
                    buttonText?: string | null;
                    linkField: {
                      linkType: 'internal' | 'external';
                      url?: string | null;
                      newTab?: boolean | null;
                      internalLink?: {
                        relationTo: 'pages';
                        value: number | Page;
                      } | null;
                    };
                  };
                  images?:
                    | {
                        image: number | Media;
                        caption?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'productSection';
                }
              | {
                  links?:
                    | {
                        linkText: string;
                        anchorId: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'jumpLinks';
                }
              | {
                  id: string | null;
                  blockName?: string | null;
                  blockType: 'anchor';
                }
              | {
                  jobsStyle?: ('grid' | 'list') | null;
                  /**
                   * Leave empty or set to 0 to show all jobs
                   */
                  limit?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'jobs';
                }
              | {
                  submitButton?: string | null;
                  confirmationMessage?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'ContactForm';
                }
            )[]
          | null;
        backgroundColor?: string | null;
        textColor?: ('default' | 'light' | 'dark') | null;
        backgroundImage?: (number | null) | Media;
        tileBackground?: boolean | null;
        backgroundFixed?: boolean | null;
        paddingTop?: number | null;
        paddingBottom?: number | null;
        topDivider?: ('none' | 'fade') | null;
        bottomDivider?: ('none' | 'fade') | null;
        backgroundDecorationToggle?: boolean | null;
        backgroundDecoration?: ('blurred-logo' | 'radial-glow') | null;
        backgroundDecorationPosition?: ('left' | 'right') | null;
        backgroundDecorationYPosition?: ('top' | 'center' | 'bottom') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'section';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  icon?: (number | null) | Media;
  lightVariantRequired?: boolean | null;
  lightIcon?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category?: (number | null) | Category;
  mainPostImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  publishedOn?: string | null;
  seo?: {
    /**
     * Shown in search results and browser tabs.
     */
    title?: string | null;
    /**
     * Short summary shown in search results.
     */
    description?: string | null;
    /**
     * Used for link previews (Open Graph). Recommended 1200×630.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  jobTitle?: string | null;
  department?: string | null;
  location?: string | null;
  salary?: string | null;
  level?: string | null;
  link?: string | null;
  shortDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  blocks?:
    | T
    | {
        section?:
          | T
          | {
              blocks?:
                | T
                | {
                    ContentWithMedia?:
                      | T
                      | {
                          content?: T;
                          media?: T;
                          textPosition?: T;
                          layout?: T;
                          width?: T;
                          verticalPadding?: T;
                          id?: T;
                          blockName?: T;
                        };
                    hero?:
                      | T
                      | {
                          logo?: T;
                          text?: T;
                          h1Source?: T;
                          customH1?: T;
                          backgroundImage?: T;
                          backgroundVideo?: T;
                          overlay?: T;
                          id?: T;
                          blockName?: T;
                        };
                    richText?:
                      | T
                      | {
                          content?: T;
                          fontSize?: T;
                          maxWidth?: T;
                          verticalPadding?: T;
                          id?: T;
                          blockName?: T;
                        };
                    textColumns?:
                      | T
                      | {
                          columns?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          colWidth?: T;
                          maxColWidth?: T;
                          id?: T;
                          blockName?: T;
                        };
                    button?:
                      | T
                      | {
                          text?: T;
                          image?: T;
                          buttonStyle?: T;
                          linkField?:
                            | T
                            | {
                                linkType?: T;
                                url?: T;
                                newTab?: T;
                                internalLink?: T;
                              };
                          alignment?: T;
                          id?: T;
                          blockName?: T;
                        };
                    LatestPosts?:
                      | T
                      | {
                          showAllPosts?: T;
                          numberOfPosts?: T;
                          categoryFilter?: T;
                          id?: T;
                          blockName?: T;
                        };
                    productCarousel?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                heading?: T;
                                subHeading?: T;
                                description?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    mediaGallery?:
                      | T
                      | {
                          images?:
                            | T
                            | {
                                media?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          image?: T;
                          imageShape?: T;
                          aspectRatio?: T;
                          maxWidth?: T;
                          customMaxWidth?: T;
                          id?: T;
                          blockName?: T;
                        };
                    videoEmbed?:
                      | T
                      | {
                          videoURL?: T;
                          id?: T;
                          blockName?: T;
                        };
                    productSection?:
                      | T
                      | {
                          number?: T;
                          heading?: T;
                          subheading?: T;
                          description?: T;
                          showButton?: T;
                          button?:
                            | T
                            | {
                                buttonText?: T;
                                linkField?:
                                  | T
                                  | {
                                      linkType?: T;
                                      url?: T;
                                      newTab?: T;
                                      internalLink?: T;
                                    };
                              };
                          images?:
                            | T
                            | {
                                image?: T;
                                caption?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    jumpLinks?:
                      | T
                      | {
                          links?:
                            | T
                            | {
                                linkText?: T;
                                anchorId?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    anchor?:
                      | T
                      | {
                          id?: T;
                          blockName?: T;
                        };
                    jobs?:
                      | T
                      | {
                          jobsStyle?: T;
                          limit?: T;
                          id?: T;
                          blockName?: T;
                        };
                    ContactForm?:
                      | T
                      | {
                          submitButton?: T;
                          confirmationMessage?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              backgroundColor?: T;
              textColor?: T;
              backgroundImage?: T;
              tileBackground?: T;
              backgroundFixed?: T;
              paddingTop?: T;
              paddingBottom?: T;
              topDivider?: T;
              bottomDivider?: T;
              backgroundDecorationToggle?: T;
              backgroundDecoration?: T;
              backgroundDecorationPosition?: T;
              backgroundDecorationYPosition?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  category?: T;
  mainPostImage?: T;
  content?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  publishedOn?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  jobTitle?: T;
  department?: T;
  location?: T;
  salary?: T;
  level?: T;
  link?: T;
  shortDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  lightVariantRequired?: T;
  lightIcon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navigationLinks?:
    | {
        linkText?: string | null;
        linkField: {
          linkType: 'internal' | 'external';
          url?: string | null;
          newTab?: boolean | null;
          internalLink?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
        };
        id?: string | null;
      }[]
    | null;
  callToAction: {
    linkText?: string | null;
    linkField: {
      linkType: 'internal' | 'external';
      url?: string | null;
      newTab?: boolean | null;
      internalLink?: {
        relationTo: 'pages';
        value: number | Page;
      } | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  footerLogo?: (number | null) | Media;
  footerLinks?:
    | {
        linkText?: string | null;
        linkField: {
          linkType: 'internal' | 'external';
          url?: string | null;
          newTab?: boolean | null;
          internalLink?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Text such as copyright information shown at the bottom of the footer.
   */
  legalText?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigationLinks?:
    | T
    | {
        linkText?: T;
        linkField?:
          | T
          | {
              linkType?: T;
              url?: T;
              newTab?: T;
              internalLink?: T;
            };
        id?: T;
      };
  callToAction?:
    | T
    | {
        linkText?: T;
        linkField?:
          | T
          | {
              linkType?: T;
              url?: T;
              newTab?: T;
              internalLink?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footerLogo?: T;
  footerLinks?:
    | T
    | {
        linkText?: T;
        linkField?:
          | T
          | {
              linkType?: T;
              url?: T;
              newTab?: T;
              internalLink?: T;
            };
        id?: T;
      };
  legalText?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}